import '../models/match_outcome.dart';
import '../models/picks.dart';

/// Resolves a [PickMarket]'s outcome from a [MatchOutcome] — the picks-side
/// mirror of [QuizArchetypes]. Both consume the same shared [MatchOutcome],
/// so "who won" is computed once (by [MatchOutcomeResolver]) and never
/// re-derived independently between the XP-quiz and Oz-coin-market systems.
///
/// Only settles markets generated by this module's own convention: a market
/// id of `'<matchId>::<archetype>'` (e.g. `'760516::winner'`) with outcome
/// ids `home`/`draw`/`away`, `yes`/`no`, or `over`/`under`. Hand-authored
/// markets with bespoke ids (e.g. team-abbreviation outcome ids like
/// `'fra'`/`'par'`) are left untouched, exactly like [QuizArchetypes] leaves
/// `buildFootballQuiz`'s larger bank untouched. The market-generation hook
/// that actually produces `<matchId>::<archetype>`-shaped markets is Phase 4
/// (picks/markets parity) — this resolver is built and tested now so that
/// work only has to wire it up, not design it.
abstract final class MarketArchetypes {
  /// Returns a settled copy of [market] (status/resolvedOutcomeId/resultNote)
  /// or a voided copy when [outcome] can't support it — a market is never
  /// left `unresolved` after this runs.
  static PickMarket settle(PickMarket market, MatchOutcome outcome) {
    if (!outcome.isFullyResolved) return _void(market, 'Result unavailable');

    return switch (market.id.split('::').last) {
      'winner' => _settleWinner(market, outcome),
      'btts' => _settleTwoWay(
        market,
        outcome.bothSidesScored,
        trueId: 'yes',
        falseId: 'no',
      ),
      'total_goals_ou' => _settleOverUnder(
        market,
        outcome.totalScoreLine,
        line: 2.5,
      ),
      'total_sixes_ou' => _settleOverUnder(
        market,
        (outcome.sportSpecific['totalSixes'] as int?),
        line: 8.5,
      ),
      'first_innings_runs_ou' => _settleOverUnder(
        market,
        (outcome.sportSpecific['firstInningsRuns'] as int?),
        line: 164.5,
      ),
      'total_points_ou' => _settleOverUnder(
        market,
        outcome.totalScoreLine,
        line: 159.5,
      ),
      'total_sets_ou' => _settleOverUnder(
        market,
        (outcome.sportSpecific['totalSets'] as int?),
        line: 3.5,
      ),
      'straight_sets' => _settleTwoWay(
        market,
        (outcome.sportSpecific['straightSets'] as bool?),
        trueId: 'yes',
        falseId: 'no',
      ),
      'race_winner' => _settleRaceWinner(market, outcome),
      _ => market, // not one of this module's archetypes — leave untouched
    };
  }

  /// Motorsport has no home/away side — the field is N drivers — so unlike
  /// [_settleWinner] this matches the resolved winner's name against
  /// whichever driver outcome ids the market itself was generated with.
  /// Session results and driver-standings feeds don't always agree on
  /// surname-only vs full-name formatting (e.g. race results saying
  /// "Hamilton" where the standings/market candidates say "Lewis
  /// Hamilton"), so this falls back to substring matching on the slug
  /// before giving up. A winner outside the market's candidate list settles
  /// to `'other'` when offered, or voids rather than silently picking a
  /// wrong outcome.
  static PickMarket _settleRaceWinner(PickMarket market, MatchOutcome outcome) {
    final winnerName = outcome.sportSpecific['winnerName'] as String?;
    if (winnerName == null) return _void(market, 'Winner unavailable');
    final needle = slugifyName(winnerName);
    final matched =
        market.outcomeFor(needle) ??
        _matchBySlugContainment(market, needle) ??
        market.outcomeFor('other');
    if (matched == null) return _void(market, 'Winner unavailable');
    return market.copyWith(
      status: PickMarketStatus.settled,
      resolvedOutcomeId: matched.id,
      resultNote: winnerName,
    );
  }

  static PickOutcome? _matchBySlugContainment(PickMarket market, String needle) {
    for (final candidate in market.outcomes) {
      if (candidate.id == 'other') continue;
      final hay = slugifyName(candidate.label);
      if (hay.contains(needle) || needle.contains(hay)) return candidate;
    }
    return null;
  }

  static String slugifyName(String name) => name
      .toLowerCase()
      .replaceAll(RegExp(r'[^a-z0-9]+'), '_')
      .replaceAll(RegExp(r'^_+|_+$'), '');

  static PickMarket _settleWinner(PickMarket market, MatchOutcome outcome) {
    final outcomeId = switch (outcome.winner) {
      OutcomeSide.home => 'home',
      OutcomeSide.away => 'away',
      OutcomeSide.draw => 'draw',
      null => null,
    };
    if (outcomeId == null || market.outcomeFor(outcomeId) == null) {
      return _void(market, 'Winner unavailable');
    }
    return market.copyWith(
      status: PickMarketStatus.settled,
      resolvedOutcomeId: outcomeId,
      resultNote: market.outcomeFor(outcomeId)!.label,
    );
  }

  static PickMarket _settleTwoWay(
    PickMarket market,
    bool? value, {
    required String trueId,
    required String falseId,
  }) {
    if (value == null) return _void(market, 'Result unavailable');
    final outcomeId = value ? trueId : falseId;
    if (market.outcomeFor(outcomeId) == null) {
      return _void(market, 'Result unavailable');
    }
    return market.copyWith(
      status: PickMarketStatus.settled,
      resolvedOutcomeId: outcomeId,
      resultNote: market.outcomeFor(outcomeId)!.label,
    );
  }

  static PickMarket _settleOverUnder(
    PickMarket market,
    num? value, {
    required double line,
  }) {
    if (value == null) return _void(market, 'Result unavailable');
    final outcomeId = value > line ? 'over' : 'under';
    if (market.outcomeFor(outcomeId) == null) {
      return _void(market, 'Result unavailable');
    }
    return market.copyWith(
      status: PickMarketStatus.settled,
      resolvedOutcomeId: outcomeId,
      resultNote: '${market.outcomeFor(outcomeId)!.label} ($value)',
    );
  }

  static PickMarket _void(PickMarket market, String reason) => market.copyWith(
    status: PickMarketStatus.voided,
    voidReason: reason,
  );
}
