import 'package:flutter/material.dart';

import '../models/picks.dart';
import '../models/sport_match.dart';

abstract class PickRepository {
  Future<List<PickMarket>> markets();

  Future<PickMarket?> marketById(String marketId);
}

class MockPickRepository implements PickRepository {
  MockPickRepository() {
    _markets = _buildMarkets();
  }

  late final List<PickMarket> _markets;
  late final DateTime _now = DateTime.now();
  late final DateTime _today = DateTime(_now.year, _now.month, _now.day);

  DateTime _at(int dayOffset, int hour, [int minute = 0]) =>
      _today.add(Duration(days: dayOffset, hours: hour, minutes: minute));

  @override
  Future<List<PickMarket>> markets() async => List.unmodifiable(_markets);

  @override
  Future<PickMarket?> marketById(String marketId) async {
    for (final market in _markets) {
      if (market.id == marketId) return market;
    }
    return null;
  }

  List<PickMarket> _buildMarkets() => [
    ..._buildFifaKnockoutMarkets(),
    ...[
      PickMarket(
        id: 'fifa_fra_par_winner',
        question: 'France vs Paraguay result',
        type: PickMarketType.match,
        sport: Sport.football,
        leagueId: 'fifa',
        leagueLabel: 'FIFA',
        status: PickMarketStatus.upcoming,
        outcomes: const [
          PickOutcome(
            id: 'fra',
            label: 'France',
            probabilityPercent: 64,
            color: Color(0xff1d4ed8),
          ),
          PickOutcome(
            id: 'draw',
            label: 'Draw',
            probabilityPercent: 22,
            color: Color(0xff64748b),
          ),
          PickOutcome(
            id: 'par',
            label: 'Paraguay',
            probabilityPercent: 14,
            color: Color(0xffd7263d),
          ),
        ],
        volumeOz: 7600,
        closesAt: DateTime(2026, 7, 5, 2, 30),
        matchId: 'fifa_fra_par',
        priceHistory: _history([
          {'fra': 60, 'draw': 24, 'par': 16},
          {'fra': 62, 'draw': 23, 'par': 15},
          {'fra': 64, 'draw': 22, 'par': 14},
        ]),
        contextTitle: 'World Cup last 32',
        contextSubtitle: 'Winner after 90 minutes',
        homeLabel: 'France',
        awayLabel: 'Paraguay',
        resultNote: 'Closes at kickoff',
      ),
      PickMarket(
        id: 'fifa_fra_par_btts',
        question: 'France vs Paraguay: both teams to score?',
        type: PickMarketType.event,
        sport: Sport.football,
        leagueId: 'fifa',
        leagueLabel: 'FIFA',
        status: PickMarketStatus.upcoming,
        outcomes: const [
          PickOutcome(
            id: 'yes',
            label: 'YES',
            probabilityPercent: 51,
            color: Color(0xff36b86a),
          ),
          PickOutcome(
            id: 'no',
            label: 'NO',
            probabilityPercent: 49,
            color: Color(0xffff332e),
          ),
        ],
        volumeOz: 4200,
        closesAt: DateTime(2026, 7, 5, 2, 30),
        matchId: 'fifa_fra_par',
        priceHistory: _history([
          {'yes': 48, 'no': 52},
          {'yes': 50, 'no': 50},
          {'yes': 51, 'no': 49},
        ]),
        contextTitle: 'France vs Paraguay event',
        contextSubtitle: 'Both teams must score at least once',
        homeLabel: 'France',
        awayLabel: 'Paraguay',
        resultNote: 'Resolves at full time',
      ),
      PickMarket(
        id: 'fifa_fra_par_france_over_1_5',
        question: 'France over 1.5 goals vs Paraguay?',
        type: PickMarketType.event,
        sport: Sport.football,
        leagueId: 'fifa',
        leagueLabel: 'FIFA',
        status: PickMarketStatus.upcoming,
        outcomes: const [
          PickOutcome(
            id: 'yes',
            label: 'YES',
            probabilityPercent: 56,
            color: Color(0xff36b86a),
          ),
          PickOutcome(
            id: 'no',
            label: 'NO',
            probabilityPercent: 44,
            color: Color(0xffff332e),
          ),
        ],
        volumeOz: 3900,
        closesAt: DateTime(2026, 7, 5, 2, 30),
        matchId: 'fifa_fra_par',
        priceHistory: _history([
          {'yes': 52, 'no': 48},
          {'yes': 55, 'no': 45},
          {'yes': 56, 'no': 44},
        ]),
        contextTitle: 'France team goals',
        contextSubtitle: 'France need 2 or more goals',
        homeLabel: 'France',
        awayLabel: 'Paraguay',
        resultNote: 'Resolves at full time',
      ),
      PickMarket(
        id: 'fifa_fra_par_first_goal',
        question: 'First goal: France or Paraguay?',
        type: PickMarketType.event,
        sport: Sport.football,
        leagueId: 'fifa',
        leagueLabel: 'FIFA',
        status: PickMarketStatus.upcoming,
        outcomes: const [
          PickOutcome(
            id: 'fra',
            label: 'France',
            probabilityPercent: 62,
            color: Color(0xff1d4ed8),
          ),
          PickOutcome(
            id: 'par',
            label: 'Paraguay',
            probabilityPercent: 28,
            color: Color(0xffd7263d),
          ),
          PickOutcome(
            id: 'none',
            label: 'No goal',
            probabilityPercent: 10,
            color: Color(0xff64748b),
          ),
        ],
        volumeOz: 3100,
        closesAt: DateTime(2026, 7, 5, 2, 30),
        matchId: 'fifa_fra_par',
        priceHistory: _history([
          {'fra': 58, 'par': 30, 'none': 12},
          {'fra': 60, 'par': 29, 'none': 11},
          {'fra': 62, 'par': 28, 'none': 10},
        ]),
        contextTitle: 'Opening goal market',
        contextSubtitle: 'First official goal of the match',
        homeLabel: 'France',
        awayLabel: 'Paraguay',
        resultNote: 'Resolves after first goal or full time',
      ),
      PickMarket(
        id: 'fifa_fra_par_red_card',
        question: 'Will a red card be shown?',
        type: PickMarketType.event,
        sport: Sport.football,
        leagueId: 'fifa',
        leagueLabel: 'FIFA',
        status: PickMarketStatus.upcoming,
        outcomes: const [
          PickOutcome(
            id: 'yes',
            label: 'YES',
            probabilityPercent: 18,
            color: Color(0xff36b86a),
          ),
          PickOutcome(
            id: 'no',
            label: 'NO',
            probabilityPercent: 82,
            color: Color(0xffff332e),
          ),
        ],
        volumeOz: 2600,
        closesAt: DateTime(2026, 7, 5, 2, 30),
        matchId: 'fifa_fra_par',
        priceHistory: _history([
          {'yes': 20, 'no': 80},
          {'yes': 19, 'no': 81},
          {'yes': 18, 'no': 82},
        ]),
        contextTitle: 'Discipline event',
        contextSubtitle: 'Any player shown a straight or second-yellow red',
        homeLabel: 'France',
        awayLabel: 'Paraguay',
        resultNote: 'Resolves at full time',
      ),
      PickMarket(
        id: 'fifa_fra_irq_winner',
        question: 'France vs Iraq result',
        type: PickMarketType.match,
        sport: Sport.football,
        leagueId: 'fifa',
        leagueLabel: 'FIFA',
        status: PickMarketStatus.upcoming,
        outcomes: const [
          PickOutcome(
            id: 'fra',
            label: 'France',
            probabilityPercent: 72,
            color: Color(0xff1d4ed8),
          ),
          PickOutcome(
            id: 'draw',
            label: 'Draw',
            probabilityPercent: 17,
            color: Color(0xff64748b),
          ),
          PickOutcome(
            id: 'irq',
            label: 'Iraq',
            probabilityPercent: 11,
            color: Color(0xffdc2626),
          ),
        ],
        volumeOz: 6400,
        closesAt: DateTime(2026, 6, 22, 18),
        matchId: 'fifa_fra_irq',
        priceHistory: _history([
          {'fra': 68, 'draw': 19, 'irq': 13},
          {'fra': 70, 'draw': 18, 'irq': 12},
          {'fra': 72, 'draw': 17, 'irq': 11},
        ]),
        contextTitle: 'Group I - matchday 2',
        contextSubtitle: 'Winner after 90 minutes',
        homeLabel: 'France',
        awayLabel: 'Iraq',
        resultNote: 'Closes at kickoff',
      ),
      PickMarket(
        id: 'fifa_arg_jor_winner',
        question: 'Argentina vs Jordan result',
        type: PickMarketType.match,
        sport: Sport.football,
        leagueId: 'fifa',
        leagueLabel: 'FIFA',
        status: PickMarketStatus.upcoming,
        outcomes: const [
          PickOutcome(
            id: 'arg',
            label: 'Argentina',
            probabilityPercent: 76,
            color: Color(0xff74acdf),
          ),
          PickOutcome(
            id: 'draw',
            label: 'Draw',
            probabilityPercent: 15,
            color: Color(0xff64748b),
          ),
          PickOutcome(
            id: 'jor',
            label: 'Jordan',
            probabilityPercent: 9,
            color: Color(0xffb91c1c),
          ),
        ],
        volumeOz: 7100,
        closesAt: DateTime(2026, 6, 23, 18),
        matchId: 'fifa_arg_jor',
        priceHistory: _history([
          {'arg': 72, 'draw': 17, 'jor': 11},
          {'arg': 74, 'draw': 16, 'jor': 10},
          {'arg': 76, 'draw': 15, 'jor': 9},
        ]),
        contextTitle: 'Group J - matchday 2',
        contextSubtitle: 'Winner after 90 minutes',
        homeLabel: 'Argentina',
        awayLabel: 'Jordan',
        resultNote: 'Closes at kickoff',
      ),
      PickMarket(
        id: 'fifa_nor_sen_btts',
        question: 'Norway vs Senegal: both teams to score?',
        type: PickMarketType.event,
        sport: Sport.football,
        leagueId: 'fifa',
        leagueLabel: 'FIFA',
        status: PickMarketStatus.upcoming,
        outcomes: const [
          PickOutcome(
            id: 'yes',
            label: 'YES',
            probabilityPercent: 58,
            color: Color(0xff36b86a),
          ),
          PickOutcome(
            id: 'no',
            label: 'NO',
            probabilityPercent: 42,
            color: Color(0xffff332e),
          ),
        ],
        volumeOz: 3600,
        closesAt: DateTime(2026, 6, 22, 20, 30),
        matchId: 'fifa_nor_sen',
        priceHistory: _history([
          {'yes': 54, 'no': 46},
          {'yes': 56, 'no': 44},
          {'yes': 58, 'no': 42},
        ]),
        contextTitle: 'Group I event',
        contextSubtitle: 'Both teams must score at least once',
        homeLabel: 'Norway',
        awayLabel: 'Senegal',
        resultNote: 'Resolves at full time',
      ),
      PickMarket(
        id: 'fifa_eng_gha_over_2_5',
        question: 'England vs Ghana over 2.5 goals?',
        type: PickMarketType.event,
        sport: Sport.football,
        leagueId: 'fifa',
        leagueLabel: 'FIFA',
        status: PickMarketStatus.upcoming,
        outcomes: const [
          PickOutcome(
            id: 'yes',
            label: 'YES',
            probabilityPercent: 57,
            color: Color(0xff36b86a),
          ),
          PickOutcome(
            id: 'no',
            label: 'NO',
            probabilityPercent: 43,
            color: Color(0xffff332e),
          ),
        ],
        volumeOz: 4700,
        closesAt: DateTime(2026, 6, 23, 23),
        matchId: 'fifa_eng_gha',
        priceHistory: _history([
          {'yes': 52, 'no': 48},
          {'yes': 55, 'no': 45},
          {'yes': 57, 'no': 43},
        ]),
        contextTitle: 'Group L event',
        contextSubtitle: 'Needs 3 or more total goals',
        homeLabel: 'England',
        awayLabel: 'Ghana',
        resultNote: 'Resolves at full time',
      ),
      PickMarket(
        id: 'fifa_por_uzb_winner',
        question: 'Portugal vs Uzbekistan result',
        type: PickMarketType.match,
        sport: Sport.football,
        leagueId: 'fifa',
        leagueLabel: 'FIFA',
        status: PickMarketStatus.upcoming,
        outcomes: const [
          PickOutcome(
            id: 'por',
            label: 'Portugal',
            probabilityPercent: 67,
            color: Color(0xffb91c1c),
          ),
          PickOutcome(
            id: 'draw',
            label: 'Draw',
            probabilityPercent: 19,
            color: Color(0xff64748b),
          ),
          PickOutcome(
            id: 'uzb',
            label: 'Uzbekistan',
            probabilityPercent: 14,
            color: Color(0xff22d3ee),
          ),
        ],
        volumeOz: 5200,
        closesAt: DateTime(2026, 6, 24, 18),
        matchId: 'fifa_por_uzb',
        priceHistory: _history([
          {'por': 63, 'draw': 21, 'uzb': 16},
          {'por': 65, 'draw': 20, 'uzb': 15},
          {'por': 67, 'draw': 19, 'uzb': 14},
        ]),
        contextTitle: 'Group L - matchday 2',
        contextSubtitle: 'Winner after 90 minutes',
        homeLabel: 'Portugal',
        awayLabel: 'Uzbekistan',
        resultNote: 'Closes at kickoff',
      ),
      PickMarket(
        id: 'fifa_col_cod_clean_sheet',
        question: 'Colombia clean sheet vs Congo DR?',
        type: PickMarketType.event,
        sport: Sport.football,
        leagueId: 'fifa',
        leagueLabel: 'FIFA',
        status: PickMarketStatus.upcoming,
        outcomes: const [
          PickOutcome(
            id: 'yes',
            label: 'YES',
            probabilityPercent: 49,
            color: Color(0xff36b86a),
          ),
          PickOutcome(
            id: 'no',
            label: 'NO',
            probabilityPercent: 51,
            color: Color(0xffff332e),
          ),
        ],
        volumeOz: 2800,
        closesAt: DateTime(2026, 6, 24, 20, 30),
        matchId: 'fifa_col_cod',
        priceHistory: _history([
          {'yes': 45, 'no': 55},
          {'yes': 47, 'no': 53},
          {'yes': 49, 'no': 51},
        ]),
        contextTitle: 'Group L event',
        contextSubtitle: 'Colombia must concede 0 goals',
        homeLabel: 'Colombia',
        awayLabel: 'Congo DR',
        resultNote: 'Resolves at full time',
      ),
      PickMarket(
        id: 'fifa_nor_fra_winner',
        question: 'Norway vs France result',
        type: PickMarketType.match,
        sport: Sport.football,
        leagueId: 'fifa',
        leagueLabel: 'FIFA',
        status: PickMarketStatus.upcoming,
        outcomes: const [
          PickOutcome(
            id: 'nor',
            label: 'Norway',
            probabilityPercent: 18,
            color: Color(0xff0f4c81),
          ),
          PickOutcome(
            id: 'draw',
            label: 'Draw',
            probabilityPercent: 24,
            color: Color(0xff64748b),
          ),
          PickOutcome(
            id: 'fra',
            label: 'France',
            probabilityPercent: 58,
            color: Color(0xff1d4ed8),
          ),
        ],
        volumeOz: 5900,
        closesAt: DateTime(2026, 6, 26, 18),
        matchId: 'fifa_nor_fra',
        priceHistory: _history([
          {'nor': 21, 'draw': 25, 'fra': 54},
          {'nor': 19, 'draw': 24, 'fra': 57},
          {'nor': 18, 'draw': 24, 'fra': 58},
        ]),
        contextTitle: 'Group I decider',
        contextSubtitle: 'Winner after 90 minutes',
        homeLabel: 'Norway',
        awayLabel: 'France',
        resultNote: 'Closes at kickoff',
      ),
      PickMarket(
        id: 'fifa_aut_arg_over_3_5_corners_arg',
        question: 'Argentina over 3.5 corners vs Austria?',
        type: PickMarketType.event,
        sport: Sport.football,
        leagueId: 'fifa',
        leagueLabel: 'FIFA',
        status: PickMarketStatus.upcoming,
        outcomes: const [
          PickOutcome(
            id: 'yes',
            label: 'YES',
            probabilityPercent: 63,
            color: Color(0xff36b86a),
          ),
          PickOutcome(
            id: 'no',
            label: 'NO',
            probabilityPercent: 37,
            color: Color(0xffff332e),
          ),
        ],
        volumeOz: 4100,
        closesAt: DateTime(2026, 6, 27, 18),
        matchId: 'fifa_aut_arg',
        priceHistory: _history([
          {'yes': 58, 'no': 42},
          {'yes': 61, 'no': 39},
          {'yes': 63, 'no': 37},
        ]),
        contextTitle: 'Group J event',
        contextSubtitle: 'Argentina need 4 or more corners',
        homeLabel: 'Austria',
        awayLabel: 'Argentina',
        resultNote: 'Resolves at full time',
      ),
      PickMarket(
        id: 'fifa_pan_eng_btts',
        question: 'Panama vs England: both teams to score?',
        type: PickMarketType.event,
        sport: Sport.football,
        leagueId: 'fifa',
        leagueLabel: 'FIFA',
        status: PickMarketStatus.upcoming,
        outcomes: const [
          PickOutcome(
            id: 'yes',
            label: 'YES',
            probabilityPercent: 44,
            color: Color(0xff36b86a),
          ),
          PickOutcome(
            id: 'no',
            label: 'NO',
            probabilityPercent: 56,
            color: Color(0xffff332e),
          ),
        ],
        volumeOz: 3300,
        closesAt: DateTime(2026, 6, 27, 23),
        matchId: 'fifa_pan_eng',
        priceHistory: _history([
          {'yes': 41, 'no': 59},
          {'yes': 43, 'no': 57},
          {'yes': 44, 'no': 56},
        ]),
        contextTitle: 'Group K event',
        contextSubtitle: 'Both teams must score at least once',
        homeLabel: 'Panama',
        awayLabel: 'England',
        resultNote: 'Resolves at full time',
      ),
      PickMarket(
        id: 'fifa_2026_winner',
        question: 'Who will win FIFA World Cup 26?',
        type: PickMarketType.future,
        sport: Sport.football,
        leagueId: 'fifa',
        leagueLabel: 'FIFA',
        status: PickMarketStatus.upcoming,
        outcomes: const [
          PickOutcome(
            id: 'arg',
            label: 'Argentina',
            probabilityPercent: 16,
            color: Color(0xff74acdf),
          ),
          PickOutcome(
            id: 'fra',
            label: 'France',
            probabilityPercent: 15,
            color: Color(0xff1d4ed8),
          ),
          PickOutcome(
            id: 'eng',
            label: 'England',
            probabilityPercent: 13,
            color: Color(0xffffffff),
          ),
          PickOutcome(
            id: 'bra',
            label: 'Brazil',
            probabilityPercent: 12,
            color: Color(0xfffacc15),
          ),
          PickOutcome(
            id: 'esp',
            label: 'Spain',
            probabilityPercent: 11,
            color: Color(0xffef4444),
          ),
          PickOutcome(
            id: 'por',
            label: 'Portugal',
            probabilityPercent: 10,
            color: Color(0xffb91c1c),
          ),
          PickOutcome(
            id: 'ger',
            label: 'Germany',
            probabilityPercent: 9,
            color: Color(0xffffffff),
          ),
          PickOutcome(
            id: 'ned',
            label: 'Netherlands',
            probabilityPercent: 7,
            color: Color(0xffff7a00),
          ),
          PickOutcome(
            id: 'uru',
            label: 'Uruguay',
            probabilityPercent: 4,
            color: Color(0xff38bdf8),
          ),
          PickOutcome(
            id: 'bel',
            label: 'Belgium',
            probabilityPercent: 3,
            color: Color(0xfff59e0b),
          ),
        ],
        volumeOz: 9800,
        closesAt: DateTime(2026, 7, 19, 23, 30),
        priceHistory: _history([
          {
            'arg': 15,
            'fra': 15,
            'eng': 12,
            'bra': 13,
            'esp': 10,
            'por': 10,
            'ger': 9,
            'ned': 7,
            'uru': 5,
            'bel': 4,
          },
          {
            'arg': 16,
            'fra': 15,
            'eng': 13,
            'bra': 12,
            'esp': 11,
            'por': 10,
            'ger': 9,
            'ned': 7,
            'uru': 4,
            'bel': 3,
          },
        ]),
        contextTitle: 'Tournament future',
        contextSubtitle: 'Open through the knockout run',
        resultNote: 'Resolves after the final',
      ),
      PickMarket(
        id: 'ipl_pjk_rcb_winner',
        question: 'Punjab vs Bangalore winner',
        type: PickMarketType.match,
        sport: Sport.cricket,
        leagueId: 'ipl',
        leagueLabel: 'IPL',
        status: PickMarketStatus.live,
        outcomes: const [
          PickOutcome(
            id: 'pjk',
            label: 'Punjab',
            probabilityPercent: 32,
            color: Color(0xffdf101d),
          ),
          PickOutcome(
            id: 'rcb',
            label: 'Bangalore',
            probabilityPercent: 68,
            color: Color(0xffffd000),
          ),
        ],
        volumeOz: 2400,
        closesAt: _now.add(const Duration(minutes: 28)),
        matchId: 'ipl_pjk_rcb',
        priceHistory: _history([
          {'pjk': 41, 'rcb': 59},
          {'pjk': 38, 'rcb': 62},
          {'pjk': 34, 'rcb': 66},
          {'pjk': 32, 'rcb': 68},
        ]),
        contextTitle: 'Live chase',
        contextSubtitle: 'RCB need 42 from 24 balls',
        homeLabel: 'Punjab',
        awayLabel: 'Bangalore',
        homeScore: '221-4 (20 ov)',
        awayScore: '180-5 (16 ov)',
        liveLabel: 'LIVE',
        resultNote: 'Ends after match',
      ),
      PickMarket(
        id: 'epl_liv_mc_winner',
        question: 'Liverpool vs Man City result',
        type: PickMarketType.match,
        sport: Sport.football,
        leagueId: 'epl',
        leagueLabel: 'EPL',
        status: PickMarketStatus.upcoming,
        outcomes: const [
          PickOutcome(
            id: 'liv',
            label: 'Liverpool',
            probabilityPercent: 38,
            color: Color(0xffc8102e),
          ),
          PickOutcome(
            id: 'draw',
            label: 'Draw',
            probabilityPercent: 26,
            color: Color(0xff64748b),
          ),
          PickOutcome(
            id: 'mc',
            label: 'Man City',
            probabilityPercent: 36,
            color: Color(0xff6cabdd),
          ),
        ],
        volumeOz: 1900,
        closesAt: _at(0, 15),
        matchId: 'epl_liv_mc',
        priceHistory: _history([
          {'liv': 35, 'draw': 28, 'mc': 37},
          {'liv': 37, 'draw': 27, 'mc': 36},
          {'liv': 38, 'draw': 26, 'mc': 36},
        ]),
        contextTitle: 'Kickoff today',
        contextSubtitle: 'Winner after 90 minutes',
        homeLabel: 'Liverpool',
        awayLabel: 'Man City',
        resultNote: 'Closes at kickoff',
      ),
      PickMarket(
        id: 'fifa_arg_por_final',
        question: 'Will Argentina or Portugal reach FIFA 26 Finals?',
        type: PickMarketType.event,
        sport: Sport.football,
        leagueId: 'fifa',
        leagueLabel: 'FIFA',
        status: PickMarketStatus.live,
        outcomes: _fifaFinalsOutcomes(),
        volumeOz: _fifaFinalsVolumeOz(),
        closesAt: DateTime(2026, 7, 19, 23, 30),
        priceHistory: _fifaFinalsHistory(),
        contextTitle: '${_fifaFinalsBetSeeds.length} real app bets',
        contextSubtitle: 'Argentina or Portugal to reach the FIFA 26 final',
        liveLabel: 'LIVE',
        resultNote: 'Market resolves when the FIFA 26 finalists are confirmed',
      ),
      PickMarket(
        id: 'ipl_sixes_over_12_5',
        question: 'Total sixes over 12.5?',
        type: PickMarketType.event,
        sport: Sport.cricket,
        leagueId: 'ipl',
        leagueLabel: 'IPL',
        status: PickMarketStatus.live,
        outcomes: const [
          PickOutcome(
            id: 'yes',
            label: 'YES',
            probabilityPercent: 41,
            color: Color(0xff36b86a),
          ),
          PickOutcome(
            id: 'no',
            label: 'NO',
            probabilityPercent: 59,
            color: Color(0xffff332e),
          ),
        ],
        volumeOz: 1260,
        closesAt: _now.add(const Duration(minutes: 16)),
        priceHistory: _history([
          {'yes': 33, 'no': 67},
          {'yes': 36, 'no': 64},
          {'yes': 39, 'no': 61},
          {'yes': 41, 'no': 59},
        ]),
        contextTitle: '9 sixes hit',
        contextSubtitle: 'Need 4 more for YES',
        liveLabel: 'LIVE',
        resultNote: 'Locks near innings end',
      ),
      PickMarket(
        id: 'ipl_2026_winner',
        question: 'Who will win IPL 2026?',
        type: PickMarketType.future,
        sport: Sport.cricket,
        leagueId: 'ipl',
        leagueLabel: 'IPL',
        status: PickMarketStatus.upcoming,
        outcomes: const [
          PickOutcome(
            id: 'mi',
            label: 'Mumbai',
            probabilityPercent: 15,
            color: Color(0xff2856a5),
          ),
          PickOutcome(
            id: 'csk',
            label: 'Chennai',
            probabilityPercent: 13,
            color: Color(0xffffd400),
          ),
          PickOutcome(
            id: 'rcb',
            label: 'Bangalore',
            probabilityPercent: 12,
            color: Color(0xffd81920),
          ),
          PickOutcome(
            id: 'kkr',
            label: 'Kolkata',
            probabilityPercent: 11,
            color: Color(0xff8b5cf6),
          ),
          PickOutcome(
            id: 'srh',
            label: 'Hyderabad',
            probabilityPercent: 10,
            color: Color(0xffff7a00),
          ),
          PickOutcome(
            id: 'rr',
            label: 'Rajasthan',
            probabilityPercent: 9,
            color: Color(0xffe91e8f),
          ),
          PickOutcome(
            id: 'gt',
            label: 'Gujarat',
            probabilityPercent: 9,
            color: Color(0xff1f3c88),
          ),
          PickOutcome(
            id: 'dc',
            label: 'Delhi',
            probabilityPercent: 8,
            color: Color(0xff174ea6),
          ),
          PickOutcome(
            id: 'lsg',
            label: 'Lucknow',
            probabilityPercent: 7,
            color: Color(0xff16a8d8),
          ),
          PickOutcome(
            id: 'pbks',
            label: 'Punjab',
            probabilityPercent: 6,
            color: Color(0xffdf101d),
          ),
        ],
        volumeOz: 8100,
        closesAt: _at(35, 20),
        priceHistory: _history([
          {
            'mi': 14,
            'csk': 14,
            'rcb': 11,
            'kkr': 10,
            'srh': 10,
            'rr': 10,
            'gt': 9,
            'dc': 8,
            'lsg': 7,
            'pbks': 7,
          },
          {
            'mi': 15,
            'csk': 13,
            'rcb': 12,
            'kkr': 11,
            'srh': 10,
            'rr': 9,
            'gt': 9,
            'dc': 8,
            'lsg': 7,
            'pbks': 6,
          },
          {
            'mi': 15,
            'csk': 13,
            'rcb': 12,
            'kkr': 11,
            'srh': 10,
            'rr': 9,
            'gt': 9,
            'dc': 8,
            'lsg': 7,
            'pbks': 6,
          },
        ]),
        contextTitle: 'Season future',
        contextSubtitle: 'All IPL teams priced from current form',
        resultNote: 'Season open',
      ),
      PickMarket(
        id: 'epl_mu_over_1_5',
        question: 'Man Utd over 1.5 goals?',
        type: PickMarketType.event,
        sport: Sport.football,
        leagueId: 'epl',
        leagueLabel: 'EPL',
        status: PickMarketStatus.settled,
        outcomes: const [
          PickOutcome(
            id: 'yes',
            label: 'YES',
            probabilityPercent: 64,
            color: Color(0xff36b86a),
          ),
          PickOutcome(
            id: 'no',
            label: 'NO',
            probabilityPercent: 36,
            color: Color(0xffff332e),
          ),
        ],
        volumeOz: 760,
        closesAt: _at(-3, 19, 30),
        matchId: 'epl_mu_whu',
        priceHistory: _history([
          {'yes': 54, 'no': 46},
          {'yes': 58, 'no': 42},
          {'yes': 64, 'no': 36},
        ]),
        contextTitle: 'Man Utd 2 - 1 West Ham',
        contextSubtitle: 'Full time',
        homeLabel: 'Man Utd',
        awayLabel: 'West Ham',
        homeScore: '2',
        awayScore: '1',
        resultNote: 'Man Utd scored 2',
        resolvedOutcomeId: 'yes',
      ),
      PickMarket(
        id: 'epl_avl_bha_double_chance',
        question: 'Brighton or draw?',
        type: PickMarketType.match,
        sport: Sport.football,
        leagueId: 'epl',
        leagueLabel: 'EPL',
        status: PickMarketStatus.settled,
        outcomes: const [
          PickOutcome(
            id: 'avl',
            label: 'Aston Villa',
            probabilityPercent: 56,
            color: Color(0xff7a003c),
          ),
          PickOutcome(
            id: 'bha_draw',
            label: 'Brighton or Draw',
            probabilityPercent: 44,
            color: Color(0xff0057b8),
          ),
        ],
        volumeOz: 940,
        closesAt: _at(-2, 19, 45),
        matchId: 'epl_avl_bha',
        priceHistory: _history([
          {'avl': 49, 'bha_draw': 51},
          {'avl': 53, 'bha_draw': 47},
          {'avl': 56, 'bha_draw': 44},
        ]),
        contextTitle: 'Aston Villa 2 - 0 Brighton',
        contextSubtitle: 'Full time',
        homeLabel: 'Aston Villa',
        awayLabel: 'Brighton',
        homeScore: '2',
        awayScore: '0',
        resultNote: 'Villa won 2-0',
        resolvedOutcomeId: 'avl',
      ),
      PickMarket(
        id: 'ipl_opener_50',
        question: 'Any opener scores 50+?',
        type: PickMarketType.event,
        sport: Sport.cricket,
        leagueId: 'ipl',
        leagueLabel: 'IPL',
        status: PickMarketStatus.unresolved,
        outcomes: const [
          PickOutcome(
            id: 'yes',
            label: 'YES',
            probabilityPercent: 62,
            color: Color(0xff36b86a),
          ),
          PickOutcome(
            id: 'no',
            label: 'NO',
            probabilityPercent: 38,
            color: Color(0xffff332e),
          ),
        ],
        volumeOz: 1180,
        closesAt: _at(-1, 15),
        matchId: 'ipl_csk_mi',
        priceHistory: _history([
          {'yes': 57, 'no': 43},
          {'yes': 61, 'no': 39},
          {'yes': 62, 'no': 38},
        ]),
        contextTitle: 'Chennai vs Mumbai',
        contextSubtitle: 'Awaiting official scorecard',
        resultNote: 'Result pending',
      ),
      PickMarket(
        id: 'ipl_rain_delay',
        question: 'Will rain delay Chennai vs Mumbai?',
        type: PickMarketType.event,
        sport: Sport.cricket,
        leagueId: 'ipl',
        leagueLabel: 'IPL',
        status: PickMarketStatus.voided,
        outcomes: const [
          PickOutcome(
            id: 'yes',
            label: 'YES',
            probabilityPercent: 22,
            color: Color(0xff36b86a),
          ),
          PickOutcome(
            id: 'no',
            label: 'NO',
            probabilityPercent: 78,
            color: Color(0xffff332e),
          ),
        ],
        volumeOz: 420,
        closesAt: _at(-1, 14),
        matchId: 'ipl_csk_mi',
        priceHistory: _history([
          {'yes': 28, 'no': 72},
          {'yes': 24, 'no': 76},
          {'yes': 22, 'no': 78},
        ]),
        contextTitle: 'Market voided',
        contextSubtitle: 'Official feed did not confirm delay timing',
        resultNote: 'Stake refunded',
        voidReason: 'Official timing source unavailable',
      ),
      // ── Belgian Grand Prix (Spa-Francorchamps) — open race-weekend markets ──
      PickMarket(
        id: 'f1_belgian_gp_winner',
        question: 'Who wins the Belgian Grand Prix?',
        type: PickMarketType.future,
        sport: Sport.f1,
        leagueId: 'f1',
        leagueLabel: 'F1',
        status: PickMarketStatus.upcoming,
        outcomes: const [
          PickOutcome(
            id: 'lec',
            label: 'Leclerc',
            probabilityPercent: 26,
            color: Color(0xffe8002d),
          ),
          PickOutcome(
            id: 'rus',
            label: 'Russell',
            probabilityPercent: 20,
            color: Color(0xff27f4d2),
          ),
          PickOutcome(
            id: 'nor',
            label: 'Norris',
            probabilityPercent: 18,
            color: Color(0xffff8000),
          ),
          PickOutcome(
            id: 'ham',
            label: 'Hamilton',
            probabilityPercent: 14,
            color: Color(0xffb91c2e),
          ),
          PickOutcome(
            id: 'ver',
            label: 'Verstappen',
            probabilityPercent: 13,
            color: Color(0xff3671c6),
          ),
          PickOutcome(
            id: 'field',
            label: 'The Field',
            probabilityPercent: 9,
            color: Color(0xff64748b),
          ),
        ],
        volumeOz: 6400,
        closesAt: DateTime(2026, 7, 26, 15, 0),
        matchId: 'f1_belgian_gp',
        priceHistory: _history([
          {'lec': 23, 'rus': 21, 'nor': 18, 'ham': 15, 'ver': 13, 'field': 10},
          {'lec': 25, 'rus': 20, 'nor': 18, 'ham': 14, 'ver': 13, 'field': 10},
          {'lec': 26, 'rus': 20, 'nor': 18, 'ham': 14, 'ver': 13, 'field': 9},
        ]),
        contextTitle: 'Belgian Grand Prix',
        contextSubtitle: 'Spa-Francorchamps · race winner',
        resultNote: 'Closes at lights out',
      ),
      PickMarket(
        id: 'f1_belgian_gp_pole',
        question: 'Who takes pole at Spa?',
        type: PickMarketType.future,
        sport: Sport.f1,
        leagueId: 'f1',
        leagueLabel: 'F1',
        status: PickMarketStatus.upcoming,
        outcomes: const [
          PickOutcome(
            id: 'lec',
            label: 'Leclerc',
            probabilityPercent: 30,
            color: Color(0xffe8002d),
          ),
          PickOutcome(
            id: 'rus',
            label: 'Russell',
            probabilityPercent: 24,
            color: Color(0xff27f4d2),
          ),
          PickOutcome(
            id: 'nor',
            label: 'Norris',
            probabilityPercent: 20,
            color: Color(0xffff8000),
          ),
          PickOutcome(
            id: 'ver',
            label: 'Verstappen',
            probabilityPercent: 16,
            color: Color(0xff3671c6),
          ),
          PickOutcome(
            id: 'field',
            label: 'The Field',
            probabilityPercent: 10,
            color: Color(0xff64748b),
          ),
        ],
        volumeOz: 3900,
        closesAt: DateTime(2026, 7, 25, 15, 0),
        matchId: 'f1_belgian_gp',
        priceHistory: _history([
          {'lec': 27, 'rus': 24, 'nor': 21, 'ver': 17, 'field': 11},
          {'lec': 29, 'rus': 24, 'nor': 20, 'ver': 16, 'field': 11},
          {'lec': 30, 'rus': 24, 'nor': 20, 'ver': 16, 'field': 10},
        ]),
        contextTitle: 'Belgian Grand Prix',
        contextSubtitle: 'Saturday qualifying · pole sitter',
        resultNote: 'Closes at Q1 start',
      ),
      PickMarket(
        id: 'f1_belgian_gp_rain',
        question: 'Will it rain during the Belgian GP?',
        type: PickMarketType.event,
        sport: Sport.f1,
        leagueId: 'f1',
        leagueLabel: 'F1',
        status: PickMarketStatus.upcoming,
        outcomes: const [
          PickOutcome(
            id: 'yes',
            label: 'YES',
            probabilityPercent: 45,
            color: Color(0xff36b86a),
          ),
          PickOutcome(
            id: 'no',
            label: 'NO',
            probabilityPercent: 55,
            color: Color(0xffff332e),
          ),
        ],
        volumeOz: 5200,
        closesAt: DateTime(2026, 7, 26, 15, 0),
        matchId: 'f1_belgian_gp',
        priceHistory: _history([
          {'yes': 38, 'no': 62},
          {'yes': 42, 'no': 58},
          {'yes': 45, 'no': 55},
        ]),
        contextTitle: 'Belgian Grand Prix',
        contextSubtitle: 'Spa weather · rain on track during the race',
        resultNote: 'Resolves at chequered flag',
      ),
      PickMarket(
        id: 'f1_belgian_gp_safety_car',
        question: 'Safety car during the Belgian GP?',
        type: PickMarketType.event,
        sport: Sport.f1,
        leagueId: 'f1',
        leagueLabel: 'F1',
        status: PickMarketStatus.upcoming,
        outcomes: const [
          PickOutcome(
            id: 'yes',
            label: 'YES',
            probabilityPercent: 58,
            color: Color(0xff36b86a),
          ),
          PickOutcome(
            id: 'no',
            label: 'NO',
            probabilityPercent: 42,
            color: Color(0xffff332e),
          ),
        ],
        volumeOz: 3100,
        closesAt: DateTime(2026, 7, 26, 15, 0),
        matchId: 'f1_belgian_gp',
        priceHistory: _history([
          {'yes': 54, 'no': 46},
          {'yes': 56, 'no': 44},
          {'yes': 58, 'no': 42},
        ]),
        contextTitle: 'Belgian Grand Prix',
        contextSubtitle: 'Full or virtual safety car deployed',
        resultNote: 'Resolves at chequered flag',
      ),
      PickMarket(
        id: 'f1_belgian_gp_verstappen_podium',
        question: 'Verstappen to finish on the podium?',
        type: PickMarketType.event,
        sport: Sport.f1,
        leagueId: 'f1',
        leagueLabel: 'F1',
        status: PickMarketStatus.upcoming,
        outcomes: const [
          PickOutcome(
            id: 'yes',
            label: 'YES',
            probabilityPercent: 47,
            color: Color(0xff36b86a),
          ),
          PickOutcome(
            id: 'no',
            label: 'NO',
            probabilityPercent: 53,
            color: Color(0xffff332e),
          ),
        ],
        volumeOz: 2600,
        closesAt: DateTime(2026, 7, 26, 15, 0),
        matchId: 'f1_belgian_gp',
        priceHistory: _history([
          {'yes': 43, 'no': 57},
          {'yes': 45, 'no': 55},
          {'yes': 47, 'no': 53},
        ]),
        contextTitle: 'Belgian Grand Prix',
        contextSubtitle: 'Max Verstappen · top-3 finish',
        resultNote: 'Resolves at chequered flag',
      ),
    ].where(_keepStaticMarket),
  ];

  bool _keepStaticMarket(PickMarket market) =>
      market.leagueId != 'fifa' || market.matchId == null;

  List<PickMarket> _buildFifaKnockoutMarkets() => [
    for (final fixture in _fifaKnockoutFixtures())
      ..._marketsForFixture(fixture),
  ];

  List<PickMarket> _marketsForFixture(_FifaKnockoutFixture fixture) {
    final status = _statusFor(fixture.kickoff);
    final seed = _stableSeed(fixture.id);
    final homeWin = 46 + seed % 23;
    final draw = 18 + seed % 8;
    final awayWin = 100 - homeWin - draw;
    final bttsYes = 43 + seed % 19;
    final firstHome = 46 + seed % 20;
    final firstAway = 84 - firstHome;
    final teamGoalsYes = 39 + seed % 22;
    final redCardYes = 14 + seed % 13;

    return [
      PickMarket(
        id: '${fixture.id}_winner',
        question: '${fixture.home} vs ${fixture.away} result',
        type: PickMarketType.match,
        sport: Sport.football,
        leagueId: 'fifa',
        leagueLabel: 'FIFA',
        status: status,
        outcomes: [
          PickOutcome(
            id: fixture.homeId,
            label: fixture.home,
            probabilityPercent: homeWin,
            color: fixture.homeColor,
          ),
          const PickOutcome(
            id: 'draw',
            label: 'Draw',
            probabilityPercent: 20,
            color: Color(0xff64748b),
          ).copyWith(probabilityPercent: draw),
          PickOutcome(
            id: fixture.awayId,
            label: fixture.away,
            probabilityPercent: awayWin,
            color: fixture.awayColor,
          ),
        ],
        volumeOz: 4200 + seed % 5200,
        closesAt: fixture.kickoff,
        matchId: fixture.id,
        priceHistory: _history([
          {
            fixture.homeId: _percent(homeWin - 4),
            'draw': _percent(draw + 2),
            fixture.awayId: _percent(awayWin + 2),
          },
          {
            fixture.homeId: _percent(homeWin - 1),
            'draw': _percent(draw),
            fixture.awayId: _percent(awayWin + 1),
          },
          {fixture.homeId: homeWin, 'draw': draw, fixture.awayId: awayWin},
        ]),
        contextTitle: fixture.roundLabel,
        contextSubtitle: 'Winner after 90 minutes',
        homeLabel: fixture.home,
        awayLabel: fixture.away,
        resultNote: _pickResultNote(status),
      ),
      PickMarket(
        id: '${fixture.id}_btts',
        question: '${fixture.home} vs ${fixture.away}: both teams to score?',
        type: PickMarketType.event,
        sport: Sport.football,
        leagueId: 'fifa',
        leagueLabel: 'FIFA',
        status: status,
        outcomes: [
          PickOutcome(
            id: 'yes',
            label: 'YES',
            probabilityPercent: bttsYes,
            color: const Color(0xff36b86a),
          ),
          PickOutcome(
            id: 'no',
            label: 'NO',
            probabilityPercent: 100 - bttsYes,
            color: const Color(0xffff332e),
          ),
        ],
        volumeOz: 2600 + seed % 3000,
        closesAt: fixture.kickoff,
        matchId: fixture.id,
        priceHistory: _yesNoHistory('yes', bttsYes),
        contextTitle: '${fixture.roundLabel} event',
        contextSubtitle: 'Both teams must score at least once',
        homeLabel: fixture.home,
        awayLabel: fixture.away,
        resultNote: 'Resolves at full time',
      ),
      PickMarket(
        id: '${fixture.id}_first_goal',
        question: 'First goal: ${fixture.home} or ${fixture.away}?',
        type: PickMarketType.event,
        sport: Sport.football,
        leagueId: 'fifa',
        leagueLabel: 'FIFA',
        status: status,
        outcomes: [
          PickOutcome(
            id: fixture.homeId,
            label: fixture.home,
            probabilityPercent: firstHome,
            color: fixture.homeColor,
          ),
          PickOutcome(
            id: fixture.awayId,
            label: fixture.away,
            probabilityPercent: firstAway,
            color: fixture.awayColor,
          ),
          const PickOutcome(
            id: 'none',
            label: 'No goal',
            probabilityPercent: 16,
            color: Color(0xff64748b),
          ),
        ],
        volumeOz: 2200 + seed % 2600,
        closesAt: fixture.kickoff,
        matchId: fixture.id,
        priceHistory: _history([
          {
            fixture.homeId: _percent(firstHome - 3),
            fixture.awayId: _percent(firstAway + 1),
            'none': 16,
          },
          {fixture.homeId: firstHome, fixture.awayId: firstAway, 'none': 16},
        ]),
        contextTitle: 'Opening goal market',
        contextSubtitle: 'First official goal of the match',
        homeLabel: fixture.home,
        awayLabel: fixture.away,
        resultNote: 'Resolves after first goal or full time',
      ),
      PickMarket(
        id: '${fixture.id}_${fixture.homeId}_over_1_5',
        question: '${fixture.home} over 1.5 goals?',
        type: PickMarketType.event,
        sport: Sport.football,
        leagueId: 'fifa',
        leagueLabel: 'FIFA',
        status: status,
        outcomes: [
          PickOutcome(
            id: 'yes',
            label: 'YES',
            probabilityPercent: teamGoalsYes,
            color: const Color(0xff36b86a),
          ),
          PickOutcome(
            id: 'no',
            label: 'NO',
            probabilityPercent: 100 - teamGoalsYes,
            color: const Color(0xffff332e),
          ),
        ],
        volumeOz: 1800 + seed % 2600,
        closesAt: fixture.kickoff,
        matchId: fixture.id,
        priceHistory: _yesNoHistory('yes', teamGoalsYes),
        contextTitle: '${fixture.home} team goals',
        contextSubtitle: '${fixture.home} need 2 or more goals',
        homeLabel: fixture.home,
        awayLabel: fixture.away,
        resultNote: 'Resolves at full time',
      ),
      PickMarket(
        id: '${fixture.id}_red_card',
        question: 'Will a red card be shown?',
        type: PickMarketType.event,
        sport: Sport.football,
        leagueId: 'fifa',
        leagueLabel: 'FIFA',
        status: status,
        outcomes: [
          PickOutcome(
            id: 'yes',
            label: 'YES',
            probabilityPercent: redCardYes,
            color: const Color(0xff36b86a),
          ),
          PickOutcome(
            id: 'no',
            label: 'NO',
            probabilityPercent: 100 - redCardYes,
            color: const Color(0xffff332e),
          ),
        ],
        volumeOz: 1400 + seed % 2200,
        closesAt: fixture.kickoff,
        matchId: fixture.id,
        priceHistory: _yesNoHistory('yes', redCardYes),
        contextTitle: 'Discipline event',
        contextSubtitle: 'Any player shown a straight or second-yellow red',
        homeLabel: fixture.home,
        awayLabel: fixture.away,
        resultNote: 'Resolves at full time',
      ),
    ];
  }

  PickMarketStatus _statusFor(DateTime kickoff) {
    if (_now.isBefore(kickoff)) return PickMarketStatus.upcoming;
    if (_now.isBefore(kickoff.add(const Duration(minutes: 125)))) {
      return PickMarketStatus.live;
    }
    return PickMarketStatus.closed;
  }

  String _pickResultNote(PickMarketStatus status) => switch (status) {
    PickMarketStatus.upcoming => 'Closes at kickoff',
    PickMarketStatus.live => 'Market live',
    _ => 'Market closed',
  };

  List<PickPricePoint> _yesNoHistory(String yesId, int yes) => _history([
    {yesId: _percent(yes - 3), 'no': _percent(103 - yes)},
    {yesId: _percent(yes), 'no': _percent(100 - yes)},
  ]);

  int _percent(int value) => value.clamp(1, 98).toInt();

  int _stableSeed(String value) {
    var hash = 17;
    for (final unit in value.codeUnits) {
      hash = (hash * 31 + unit) % 100000;
    }
    return hash;
  }

  List<_FifaKnockoutFixture> _fifaKnockoutFixtures() => [
    _FifaKnockoutFixture(
      'fifa_r32_mex_rsa',
      'Round of 32',
      'mex',
      'Mexico',
      const Color(0xff16a34a),
      'rsa',
      'South Africa',
      const Color(0xff16a34a),
      DateTime(2026, 6, 28, 18),
    ),
    _FifaKnockoutFixture(
      'fifa_r32_bra_jpn',
      'Round of 32',
      'bra',
      'Brazil',
      const Color(0xfffacc15),
      'jpn',
      'Japan',
      const Color(0xffffffff),
      DateTime(2026, 6, 28, 20, 30),
    ),
    _FifaKnockoutFixture(
      'fifa_r32_ger_par',
      'Round of 32',
      'ger',
      'Germany',
      const Color(0xffffffff),
      'par',
      'Paraguay',
      const Color(0xffd7263d),
      DateTime(2026, 6, 28, 23),
    ),
    _FifaKnockoutFixture(
      'fifa_r32_ned_mar',
      'Round of 32',
      'ned',
      'Netherlands',
      const Color(0xffff7a00),
      'mar',
      'Morocco',
      const Color(0xffc1272d),
      DateTime(2026, 6, 29, 18),
    ),
    _FifaKnockoutFixture(
      'fifa_r32_fra_swe',
      'Round of 32',
      'fra',
      'France',
      const Color(0xff1d4ed8),
      'swe',
      'Sweden',
      const Color(0xfffacc15),
      DateTime(2026, 6, 29, 20, 30),
    ),
    _FifaKnockoutFixture(
      'fifa_r32_arg_cpv',
      'Round of 32',
      'arg',
      'Argentina',
      const Color(0xff74acdf),
      'cpv',
      'Cabo Verde',
      const Color(0xff2563eb),
      DateTime(2026, 6, 29, 23),
    ),
    _FifaKnockoutFixture(
      'fifa_r32_por_cro',
      'Round of 32',
      'por',
      'Portugal',
      const Color(0xffb91c1c),
      'cro',
      'Croatia',
      const Color(0xff1d4ed8),
      DateTime(2026, 6, 30, 18),
    ),
    _FifaKnockoutFixture(
      'fifa_r32_usa_sen',
      'Round of 32',
      'usa',
      'United States',
      const Color(0xff2563eb),
      'sen',
      'Senegal',
      const Color(0xff16a34a),
      DateTime(2026, 6, 30, 20, 30),
    ),
    _FifaKnockoutFixture(
      'fifa_r32_eng_gha',
      'Round of 32',
      'eng',
      'England',
      const Color(0xffffffff),
      'gha',
      'Ghana',
      const Color(0xfffacc15),
      DateTime(2026, 7, 1, 18),
    ),
    _FifaKnockoutFixture(
      'fifa_r32_esp_aut',
      'Round of 32',
      'esp',
      'Spain',
      const Color(0xfff59e0b),
      'aut',
      'Austria',
      const Color(0xffef4444),
      DateTime(2026, 7, 1, 20, 30),
    ),
    _FifaKnockoutFixture(
      'fifa_r32_bel_ira',
      'Round of 32',
      'bel',
      'Belgium',
      const Color(0xfffacc15),
      'irq',
      'Iraq',
      const Color(0xffdc2626),
      DateTime(2026, 7, 2, 18),
    ),
    _FifaKnockoutFixture(
      'fifa_r32_nor_egy',
      'Round of 32',
      'nor',
      'Norway',
      const Color(0xff0f4c81),
      'egy',
      'Egypt',
      const Color(0xffdc2626),
      DateTime(2026, 7, 2, 20, 30),
    ),
    _FifaKnockoutFixture(
      'fifa_r32_sui_alg',
      'Round of 32',
      'sui',
      'Switzerland',
      const Color(0xffef4444),
      'alg',
      'Algeria',
      const Color(0xff059669),
      DateTime(2026, 7, 3, 18),
    ),
    _FifaKnockoutFixture(
      'fifa_r32_can_col',
      'Round of 32',
      'can',
      'Canada',
      const Color(0xffef4444),
      'col',
      'Colombia',
      const Color(0xfffacc15),
      DateTime(2026, 7, 3, 20, 30),
    ),
    _FifaKnockoutFixture(
      'fifa_r32_pan_uzb',
      'Round of 32',
      'pan',
      'Panama',
      const Color(0xff2563eb),
      'uzb',
      'Uzbekistan',
      const Color(0xff22d3ee),
      DateTime(2026, 7, 3, 23),
    ),
    _FifaKnockoutFixture(
      'fifa_r32_jor_cod',
      'Round of 32',
      'jor',
      'Jordan',
      const Color(0xffb91c1c),
      'cod',
      'Congo DR',
      const Color(0xff38bdf8),
      DateTime(2026, 7, 3, 23, 30),
    ),
    _FifaKnockoutFixture(
      'fifa_r16_can_mar',
      'Round of 16',
      'can',
      'Canada',
      const Color(0xffef4444),
      'mar',
      'Morocco',
      const Color(0xffc1272d),
      DateTime(2026, 7, 4, 18),
    ),
    _FifaKnockoutFixture(
      'fifa_fra_par',
      'Round of 16',
      'fra',
      'France',
      const Color(0xff1d4ed8),
      'par',
      'Paraguay',
      const Color(0xffd7263d),
      DateTime(2026, 7, 5, 2, 30),
    ),
    _FifaKnockoutFixture(
      'fifa_r16_bra_nor',
      'Round of 16',
      'bra',
      'Brazil',
      const Color(0xfffacc15),
      'nor',
      'Norway',
      const Color(0xff0f4c81),
      DateTime(2026, 7, 5, 18),
    ),
    _FifaKnockoutFixture(
      'fifa_r16_mex_eng',
      'Round of 16',
      'mex',
      'Mexico',
      const Color(0xff16a34a),
      'eng',
      'England',
      const Color(0xffffffff),
      DateTime(2026, 7, 5, 23),
    ),
    _FifaKnockoutFixture(
      'fifa_r16_por_esp',
      'Round of 16',
      'por',
      'Portugal',
      const Color(0xffb91c1c),
      'esp',
      'Spain',
      const Color(0xfff59e0b),
      DateTime(2026, 7, 6, 18),
    ),
    _FifaKnockoutFixture(
      'fifa_r16_usa_bel',
      'Round of 16',
      'usa',
      'United States',
      const Color(0xff2563eb),
      'bel',
      'Belgium',
      const Color(0xfffacc15),
      DateTime(2026, 7, 6, 23),
    ),
    _FifaKnockoutFixture(
      'fifa_r16_arg_egy',
      'Round of 16',
      'arg',
      'Argentina',
      const Color(0xff74acdf),
      'egy',
      'Egypt',
      const Color(0xffdc2626),
      DateTime(2026, 7, 7, 18),
    ),
    _FifaKnockoutFixture(
      'fifa_r16_sui_col',
      'Round of 16',
      'sui',
      'Switzerland',
      const Color(0xffef4444),
      'col',
      'Colombia',
      const Color(0xfffacc15),
      DateTime(2026, 7, 7, 23),
    ),
    _FifaKnockoutFixture(
      'fifa_qf_mar_fra',
      'Quarterfinal',
      'mar',
      'Morocco',
      const Color(0xffc1272d),
      'fra',
      'France',
      const Color(0xff1d4ed8),
      DateTime(2026, 7, 9, 23),
    ),
    _FifaKnockoutFixture(
      'fifa_qf_por_bel',
      'Quarterfinal',
      'por',
      'Portugal',
      const Color(0xffb91c1c),
      'bel',
      'Belgium',
      const Color(0xfffacc15),
      DateTime(2026, 7, 10, 23),
    ),
    _FifaKnockoutFixture(
      'fifa_qf_nor_eng',
      'Quarterfinal',
      'nor',
      'Norway',
      const Color(0xff0f4c81),
      'eng',
      'England',
      const Color(0xffffffff),
      DateTime(2026, 7, 11, 18),
    ),
    _FifaKnockoutFixture(
      'fifa_qf_arg_col',
      'Quarterfinal',
      'arg',
      'Argentina',
      const Color(0xff74acdf),
      'col',
      'Colombia',
      const Color(0xfffacc15),
      DateTime(2026, 7, 11, 23),
    ),
    _FifaKnockoutFixture(
      'fifa_sf_fra_bel',
      'Semifinal',
      'fra',
      'France',
      const Color(0xff1d4ed8),
      'bel',
      'Belgium',
      const Color(0xfffacc15),
      DateTime(2026, 7, 14, 23),
    ),
    _FifaKnockoutFixture(
      'fifa_sf_eng_arg',
      'Semifinal',
      'eng',
      'England',
      const Color(0xffffffff),
      'arg',
      'Argentina',
      const Color(0xff74acdf),
      DateTime(2026, 7, 15, 23),
    ),
    _FifaKnockoutFixture(
      'fifa_third_bel_eng',
      'Third-place match',
      'bel',
      'Belgium',
      const Color(0xfffacc15),
      'eng',
      'England',
      const Color(0xffffffff),
      DateTime(2026, 7, 18, 20, 30),
    ),
    _FifaKnockoutFixture(
      'fifa_final_fra_arg',
      'Final',
      'fra',
      'France',
      const Color(0xff1d4ed8),
      'arg',
      'Argentina',
      const Color(0xff74acdf),
      DateTime(2026, 7, 19, 23, 30),
    ),
  ];

  List<PickOutcome> _fifaFinalsOutcomes() {
    final yes = _fifaFinalsYesPercent();
    return [
      PickOutcome(
        id: 'yes',
        label: 'YES',
        probabilityPercent: yes,
        color: const Color(0xff36b86a),
      ),
      PickOutcome(
        id: 'no',
        label: 'NO',
        probabilityPercent: 100 - yes,
        color: const Color(0xffff332e),
      ),
    ];
  }

  int _fifaFinalsYesPercent() => _yesPercentFor(_fifaFinalsBetSeeds.last);

  int _fifaFinalsVolumeOz() =>
      _fifaFinalsBetSeeds.fold(0, (total, seed) => total + seed.coinsBet);

  List<PickPricePoint> _fifaFinalsHistory() => [
    for (final seed in _fifaFinalsBetSeeds)
      PickPricePoint(
        at: DateTime.parse(seed.createdAt),
        percentsByOutcome: {
          'yes': _yesPercentFor(seed),
          'no': 100 - _yesPercentFor(seed),
        },
      ),
  ];

  int _yesPercentFor(_PickTradeSeed seed) {
    final selected = _cleanPercent(seed.oddsChoice);
    return seed.choice == 'Y' ? selected : 100 - selected;
  }

  int _cleanPercent(double value) {
    final rounded = value.round();
    if (rounded < 1) return 1;
    if (rounded > 99) return 99;
    return rounded;
  }

  List<PickPricePoint> _history(List<Map<String, int>> values) {
    final start = _now.subtract(Duration(minutes: values.length * 18));
    return [
      for (var i = 0; i < values.length; i++)
        PickPricePoint(
          at: start.add(Duration(minutes: i * 18)),
          percentsByOutcome: values[i],
        ),
    ];
  }
}

class _FifaKnockoutFixture {
  const _FifaKnockoutFixture(
    this.id,
    this.roundLabel,
    this.homeId,
    this.home,
    this.homeColor,
    this.awayId,
    this.away,
    this.awayColor,
    this.kickoff,
  );

  final String id;
  final String roundLabel;
  final String homeId;
  final String home;
  final Color homeColor;
  final String awayId;
  final String away;
  final Color awayColor;
  final DateTime kickoff;
}

class _PickTradeSeed {
  const _PickTradeSeed(
    this.createdAt,
    this.choice,
    this.coinsBet,
    this.oddsChoice,
  );

  final String createdAt;
  final String choice;
  final int coinsBet;
  final double oddsChoice;
}

const _fifaFinalsBetSeeds = [
  _PickTradeSeed('2026-05-31T21:42:11.373Z', 'Y', 250, 55.56),
  _PickTradeSeed('2026-06-01T01:54:34.779Z', 'N', 10, 44.69),
  _PickTradeSeed('2026-06-01T11:25:07.454Z', 'Y', 10, 55.51),
  _PickTradeSeed('2026-06-01T11:52:03.500Z', 'N', 10, 44.74),
  _PickTradeSeed('2026-06-01T12:08:49.166Z', 'Y', 60, 56.41),
  _PickTradeSeed('2026-06-01T13:25:53.566Z', 'N', 10, 43.83),
  _PickTradeSeed('2026-06-01T14:38:09.172Z', 'Y', 10, 56.36),
  _PickTradeSeed('2026-06-01T15:37:53.944Z', 'N', 1000, 60.42),
  _PickTradeSeed('2026-06-01T16:51:14.987Z', 'Y', 10, 39.76),
  _PickTradeSeed('2026-06-01T16:51:22.084Z', 'N', 10, 60.36),
  _PickTradeSeed('2026-06-01T18:13:40.522Z', 'Y', 910, 52.45),
  _PickTradeSeed('2026-06-01T19:13:12.761Z', 'Y', 260, 55.16),
  _PickTradeSeed('2026-06-01T19:13:13.611Z', 'Y', 260, 57.59),
  _PickTradeSeed('2026-06-01T19:13:29.974Z', 'Y', 10, 57.68),
  _PickTradeSeed('2026-06-01T22:09:37.807Z', 'Y', 1000, 64.95),
  _PickTradeSeed('2026-06-02T05:16:39.466Z', 'Y', 10, 65.01),
  _PickTradeSeed('2026-06-02T05:24:46.026Z', 'Y', 50, 65.31),
  _PickTradeSeed('2026-06-02T05:24:46.564Z', 'Y', 50, 65.6),
  _PickTradeSeed('2026-06-02T05:34:35.327Z', 'Y', 200, 66.72),
  _PickTradeSeed('2026-06-02T06:44:01.734Z', 'N', 1000, 42.64),
  _PickTradeSeed('2026-06-02T07:28:41.097Z', 'N', 100, 43.43),
  _PickTradeSeed('2026-06-02T09:44:08.483Z', 'Y', 1000, 61.85),
  _PickTradeSeed('2026-06-02T20:12:24.191Z', 'N', 1000, 44.85),
  _PickTradeSeed('2026-06-02T22:54:42.630Z', 'N', 100, 45.44),
  _PickTradeSeed('2026-06-03T01:22:06.246Z', 'N', 10, 45.5),
  _PickTradeSeed('2026-06-03T10:51:12.979Z', 'Y', 300, 55.91),
  _PickTradeSeed('2026-06-03T12:55:01.418Z', 'N', 10, 44.15),
  _PickTradeSeed('2026-06-03T16:38:31.325Z', 'Y', 60, 56.13),
  _PickTradeSeed('2026-06-03T21:24:15.451Z', 'N', 1000, 49.11),
  _PickTradeSeed('2026-06-04T03:48:24.276Z', 'Y', 10, 50.93),
  _PickTradeSeed('2026-06-04T03:48:25.051Z', 'Y', 10, 50.98),
  _PickTradeSeed('2026-06-04T03:50:24.040Z', 'Y', 110, 51.48),
  _PickTradeSeed('2026-06-04T03:50:25.164Z', 'Y', 110, 51.96),
  _PickTradeSeed('2026-06-04T03:50:25.295Z', 'Y', 110, 52.44),
  _PickTradeSeed('2026-06-04T04:52:13.295Z', 'Y', 10, 52.48),
  _PickTradeSeed('2026-06-04T07:18:50.532Z', 'Y', 10, 52.53),
  _PickTradeSeed('2026-06-04T08:23:47.654Z', 'Y', 10, 52.57),
  _PickTradeSeed('2026-06-04T08:32:21.319Z', 'Y', 60, 52.83),
  _PickTradeSeed('2026-06-04T09:28:23.369Z', 'Y', 10, 52.87),
  _PickTradeSeed('2026-06-04T09:28:23.626Z', 'Y', 10, 52.91),
  _PickTradeSeed('2026-06-04T09:28:34.212Z', 'Y', 10, 52.95),
  _PickTradeSeed('2026-06-04T09:28:35.308Z', 'Y', 10, 52.99),
  _PickTradeSeed('2026-06-04T10:12:29.256Z', 'Y', 10, 53.04),
  _PickTradeSeed('2026-06-05T07:36:14.288Z', 'Y', 700, 55.8),
  _PickTradeSeed('2026-06-05T13:47:33.173Z', 'Y', 10, 55.84),
  _PickTradeSeed('2026-06-05T14:01:14.330Z', 'Y', 10, 55.87),
  _PickTradeSeed('2026-06-05T14:01:18.545Z', 'Y', 10, 55.91),
  _PickTradeSeed('2026-06-05T14:41:22.234Z', 'Y', 10, 55.95),
  _PickTradeSeed('2026-06-06T01:37:04.471Z', 'N', 500, 46.3),
  _PickTradeSeed('2026-06-06T02:00:51.218Z', 'Y', 10, 53.73),
  _PickTradeSeed('2026-06-06T02:22:40.344Z', 'N', 10, 46.31),
  _PickTradeSeed('2026-06-06T07:04:09.739Z', 'Y', 260, 54.64),
  _PickTradeSeed('2026-06-06T07:04:19.036Z', 'N', 260, 46.46),
  _PickTradeSeed('2026-06-06T11:50:42.957Z', 'Y', 50, 53.72),
  _PickTradeSeed('2026-06-06T21:12:25.749Z', 'Y', 10, 53.76),
  _PickTradeSeed('2026-06-07T09:54:32.690Z', 'Y', 1000, 57.05),
  _PickTradeSeed('2026-06-07T10:12:57.216Z', 'N', 10, 42.99),
  _PickTradeSeed('2026-06-07T10:57:23.116Z', 'N', 60, 43.23),
  _PickTradeSeed('2026-06-07T12:29:51.126Z', 'Y', 10, 56.8),
  _PickTradeSeed('2026-06-07T12:30:11.787Z', 'N', 10, 43.24),
  _PickTradeSeed('2026-06-08T06:16:24.577Z', 'N', 10, 43.28),
  _PickTradeSeed('2026-06-08T07:15:51.209Z', 'Y', 10, 56.75),
  _PickTradeSeed('2026-06-08T10:03:42.428Z', 'N', 10, 43.29),
  _PickTradeSeed('2026-06-08T18:24:12.443Z', 'Y', 10, 56.74),
  _PickTradeSeed('2026-06-08T19:08:47.543Z', 'Y', 10, 56.77),
  _PickTradeSeed('2026-06-08T19:46:51.010Z', 'Y', 10, 56.8),
  _PickTradeSeed('2026-06-08T19:54:49.722Z', 'Y', 10, 56.83),
  _PickTradeSeed('2026-06-09T01:56:56.441Z', 'N', 10, 43.21),
  _PickTradeSeed('2026-06-09T01:56:56.882Z', 'N', 10, 43.25),
  _PickTradeSeed('2026-06-09T01:56:57.525Z', 'N', 10, 43.29),
  _PickTradeSeed('2026-06-09T01:57:15.626Z', 'Y', 10, 56.74),
  _PickTradeSeed('2026-06-09T01:58:01.310Z', 'Y', 60, 56.92),
  _PickTradeSeed('2026-06-09T01:59:01.697Z', 'Y', 10, 56.95),
  _PickTradeSeed('2026-06-09T14:16:42.901Z', 'N', 100, 43.44),
  _PickTradeSeed('2026-06-09T14:16:50.036Z', 'N', 100, 43.83),
  _PickTradeSeed('2026-06-09T15:39:00.715Z', 'Y', 200, 56.76),
  _PickTradeSeed('2026-06-09T20:30:03.476Z', 'Y', 1, 56.77),
  _PickTradeSeed('2026-06-09T20:30:03.919Z', 'Y', 1, 56.77),
  _PickTradeSeed('2026-06-09T20:30:03.933Z', 'Y', 1, 56.77),
  _PickTradeSeed('2026-06-09T20:30:03.953Z', 'Y', 1, 56.78),
  _PickTradeSeed('2026-06-09T20:30:04.298Z', 'Y', 1, 56.78),
  _PickTradeSeed('2026-06-09T21:03:52.778Z', 'N', 10, 43.26),
  _PickTradeSeed('2026-06-09T21:31:45.910Z', 'Y', 10, 56.77),
  _PickTradeSeed('2026-06-09T21:31:46.377Z', 'Y', 10, 56.8),
  _PickTradeSeed('2026-06-09T21:31:54.879Z', 'N', 10, 43.24),
  _PickTradeSeed('2026-06-09T21:32:20.013Z', 'Y', 10, 56.79),
  _PickTradeSeed('2026-06-09T21:32:26.259Z', 'Y', 10, 56.82),
  _PickTradeSeed('2026-06-09T21:32:32.417Z', 'N', 10, 43.22),
  _PickTradeSeed('2026-06-09T21:32:33.010Z', 'N', 10, 43.26),
  _PickTradeSeed('2026-06-09T22:20:20.497Z', 'Y', 10, 56.77),
  _PickTradeSeed('2026-06-10T01:00:33.817Z', 'Y', 60, 56.95),
  _PickTradeSeed('2026-06-10T01:01:36.367Z', 'N', 10, 43.09),
  _PickTradeSeed('2026-06-10T05:48:22.821Z', 'Y', 10, 56.94),
  _PickTradeSeed('2026-06-10T07:03:39.449Z', 'Y', 10, 56.97),
  _PickTradeSeed('2026-06-10T08:55:12.931Z', 'Y', 100, 57.25),
  _PickTradeSeed('2026-06-10T10:10:38.864Z', 'Y', 360, 58.25),
  _PickTradeSeed('2026-06-10T10:10:39.417Z', 'Y', 360, 59.21),
  _PickTradeSeed('2026-06-10T12:00:25.863Z', 'N', 10, 40.83),
  _PickTradeSeed('2026-06-10T12:00:28.401Z', 'N', 10, 40.86),
  _PickTradeSeed('2026-06-10T13:41:17.221Z', 'Y', 10, 59.16),
  _PickTradeSeed('2026-06-10T15:11:13.619Z', 'Y', 10, 59.19),
];
